import { blue, green, grey, yellow } from '@ant-design/colors';

export const Colors = {
  logoBlue: '#0057b8',
  logoYellow: '#ffd700',
  mastered: green[7] as string,
  excluded: grey[0] as string,
  awared: blue[4] as string,
  unknown: yellow[5] as string,
  yellow: yellow as unknown as readonly [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ],
  blue: blue as unknown as readonly [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ],
  green: green as unknown as readonly [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ],
  greys: grey as unknown as readonly [
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
    string,
  ],
} as const;
